### ISSUE TITLE
"No route matched for" error when using engine routes

### ISSUE THREAD

**Issue by blocknotes** [k0kubun/rspec-openapi#37] opened 2022-03-16 22:12 UTC
Hey :)
In a project we have an engine which provides some routes.
When using _rspec-openapi_ the routes seem to be missing => `No route matched for GET /test` is raised.

I reproduced the issue here: https://github.com/blocknotes/rspec-openapi/tree/issue-engine-routes/issue

- `app.rb` is a one-file Rails app;
- `vendor/my_engine` is a sample engine with a test route;
- `spec` includes the request spec that I prepared.

You can try in the `issue` folder, running `OPENAPI=1 rspec` directly.

It could be similar to #25 - but there isn't an example there.

I'm also trying a fix here: https://github.com/blocknotes/rspec-openapi/commit/1201edd26bbe7f70c1752a0371337df7ebba940a

I saw that this line https://github.com/k0kubun/rspec-openapi/blob/master/lib/rspec/openapi/record_builder.rb#L79 recognize more than a route (it looks weird), but the first one is from the engine and let fail the method.

**Comment by k0kubun** [comment] 2022-03-17 03:13
Thank you for reporting this. Since you already have a small reproduction code, could you also turn the issue directory into a working test case first that can be merged as is?

**Comment by blocknotes** [comment] 2022-03-17 07:47
> Thank you for reporting this. Since you already have a small reproduction code, could you also turn the issue directory into a working test case first that can be merged as is? Being able to see it as a draft PR would be even more helpful.

Sure => #38 
It contains also a change to support the case where there's no controller (ex. a route with only a block) and the case of 404 routes (without raising an exception).

BTW, I'm not 100% convinced right now of the third commit (the engine fix) because if the relevant route is the first one it could be ignored in the iterations of the `recognize` block.

Also, at the moment, I don't know why `recognize` catch more routes than expected.
Investigating a bit:

```rb
app.routes.recognize_path(request.path_info, method: request.method)
# => {:controller=>"hello", :action=>"world"}

routes = []; app.routes.router.recognize(request) { |route| routes << route }; routes.count
# => 2
routes.map(&:name)
# => ["my_engine", "hello_world"]
routes.map(&:defaults)
# => [{}, {:controller=>"hello", :action=>"world"}]
```

**Comment by k0kubun** [comment] 2022-03-18 03:25
Thank you for filing it. You're still not so sure about your current approach and you expect me to think about it, right? I don't have time to do that right away, so please allow me to find time to work on it.

**Comment by blocknotes** [comment] 2022-03-18 11:12
> Thank you for filing it. You're still not so sure about your current approach and you expect me to think about it, right? I don't have time to do that right away, so please allow me to find time to work on it.

Yeah, I think that the proposed fix is not optimal.
Perhaps I already found a failing edge case with it (I'm making my tests on a project with a lot of different requests).

But I will probably look for a better solution and keep you posted.

**Comment by blocknotes** [comment] 2022-03-18 13:39
Update: I think I found a better solution - PR updated.
I made some trials and it looks good now.

Please let me know your opinion.

**Comment by k0kubun** [comment] 2022-03-18 16:49
It looks like none of your currently open pull requests has a test case at this point. If you accidentally dropped it, could you resurrect it? I think this repository should have a test that runs a Rails engine.

**Comment by blocknotes** [comment] 2022-03-19 08:25
> It looks like none of your currently open pull requests has a test case at this point. If you accidentally dropped it, could you resurrect it? I think this repository should have a test that runs a Rails engine.

You are right, I have just updated the PR with an engine test.
Please check the PR carefully when you have some time 🙏 
It looks correct to me but it's a tricky part.

**Closed** 2022-03-24 23:20 UTC
